server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.8.124:3100/loki/api/v1/push
    external_labels:
      source: meshtastic-bot
      host: ${PROMTAIL_HOSTNAME}

scrape_configs:
  - job_name: systemd-journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
        source: journal
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "systemd_unit"
      - source_labels: ["__journal__hostname"]
        target_label: "host"

  - job_name: meshtastic-files
    static_configs:
      - targets: [localhost]
        labels:
          job: meshtastic-files
          source: file
          host: ${PROMTAIL_HOSTNAME}
          __path__: /var/log/meshtastic/meshtastic_stats.log*

